// <auto-generated />
namespace NotifierManager.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class AddRepeatFeatures : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddRepeatFeatures));
        
        string IMigrationMetadata.Id
        {
            get { return "202412130141051_AddRepeatFeatures"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
